image: docker:latest
services:
  - docker:dind

stages:
  - build

before_script:
  - echo Logging in to Docker Hub...
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - echo Build started on `date` for $CI_COMMIT_REF_NAME
    - if [[ "$CI_REGISTRY" =~ "master" ]]; then export build=latest done else build=$CI_REGISTRY fi
    - docker build -t richarvey/nginx-php-fpm:"$build" .
    - docker push richarvey/nginx-php-fpm:"$build"
